import 'vocab_word.dart';

/// One entry in a per-level bundle file (`assets/vocab/vocab_a1.json`
/// etc., `DATA_MODEL.md` §11.2) — the narrower, browse-only shape the
/// static bundle actually contains, as distinct from [VocabWord] (the
/// full `vocabWords` Firestore document). Deliberately does **not**
/// fabricate the Firestore-only fields the bundle excludes (`source`,
/// `addedByTeacherId`, `createdAt`/`updatedAt`) — a value read from a
/// bundle genuinely doesn't have those, and this type says so honestly
/// rather than defaulting them to something misleading.
class VocabBundleEntry {
  VocabBundleEntry({
    required this.word,
    required this.meanings,
    required this.cefrLevel,
    required this.topics,
  }) : assert(
         meanings.isNotEmpty,
         'VocabBundleEntry requires at least one meaning',
       );

  /// Already normalized (`normalizeWord(raw)`) — same as the source
  /// document's `word`/`docId`.
  final String word;

  /// Reuses [VocabMeaning] from `vocab_word.dart` rather than duplicating
  /// the meaning shape — same `pos`/`translationId` pair either way.
  final List<VocabMeaning> meanings;

  final String cefrLevel;

  final List<String> topics;

  /// **Derived, not trusted from source data** — same convention as
  /// [VocabWord.posList] (`DATA_MODEL.md` §2: "turunan otomatis... jangan
  /// diisi manual"). Always computed fresh from [meanings], never read
  /// from a source map's own `posList` value.
  List<String> get posList => [for (final meaning in meanings) meaning.pos];

  /// The documented "primary meaning" convention — `meanings[0]`.
  VocabMeaning get primaryMeaning => meanings.first;

  /// Parses one bundle entry. Mirrors [VocabWord.fromFirestore]'s plain
  /// cast style — a missing/wrong-typed required field throws a
  /// [TypeError] at the cast site, same as there.
  ///
  /// One deliberate addition beyond that style: an explicit check for an
  /// empty `meanings` list. Unlike a wrong-typed field, a well-typed but
  /// empty `meanings` array wouldn't otherwise throw at all here — the
  /// constructor's `assert` is stripped from release builds, so without
  /// this check the entry would construct "successfully" and only fail
  /// later and further away (e.g. [primaryMeaning] throwing `StateError`
  /// wherever it's first read). Throwing here instead keeps it something
  /// [listFromJson] can actually catch and skip, in every build mode.
  factory VocabBundleEntry.fromMap(Map<String, dynamic> data) {
    final meanings = [
      for (final raw in data['meanings'] as List)
        VocabMeaning.fromMap(raw as Map<String, dynamic>),
    ];
    if (meanings.isEmpty) {
      throw const FormatException(
        'VocabBundleEntry: "meanings" must have at least one element',
      );
    }

    return VocabBundleEntry(
      word: data['word'] as String,
      meanings: meanings,
      cefrLevel: data['cefrLevel'] as String,
      topics: [for (final topic in data['topics'] as List) topic as String],
    );
  }

  /// Narrows a full Firestore [VocabWord] down to the bundle-shape fields.
  /// Used when merging live delta-query results (`DATA_MODEL.md` §11.3)
  /// into an in-memory bundle list — [word]'s `source`/`addedByTeacherId`/
  /// `createdAt`/`updatedAt` are real there, but irrelevant to what browse
  /// needs, so they're intentionally dropped rather than carried along.
  factory VocabBundleEntry.fromVocabWord(VocabWord word) {
    return VocabBundleEntry(
      word: word.word,
      meanings: word.meanings,
      cefrLevel: word.cefrLevel,
      topics: word.topics,
    );
  }

  /// Inverse of [fromMap] — the 5-field bundle shape exactly, including
  /// the derived [posList] (the bundle file itself does store `posList`
  /// per `DATA_MODEL.md` §11.2, generated by the dev-side bundle script,
  /// even though this model always recomputes it rather than trusting it
  /// on the way in). Never includes `source`/`addedByTeacherId`/
  /// `createdAt`/`updatedAt` — this type doesn't have them.
  Map<String, dynamic> toMap() {
    return {
      'word': word,
      'meanings': [for (final meaning in meanings) meaning.toMap()],
      'posList': posList,
      'cefrLevel': cefrLevel,
      'topics': topics,
    };
  }

  /// Parses a whole decoded bundle array. Pure Dart — takes already-
  /// decoded JSON (e.g. the result of `jsonDecode` on a string), does no
  /// I/O of its own, and has no network/Firebase/asset-loading/Flutter UI
  /// dependency. Wiring this to an actual `rootBundle.loadString` read is
  /// a later stage's concern, not this one's.
  ///
  /// An entry that fails to parse is **skipped**, not fatal to the rest
  /// of the level — a single malformed word (e.g. a bug in the dev-side
  /// bundle generator, or a hand-edited fixture typo) shouldn't take down
  /// browsing for the other ~1000 words in that level. This deliberately
  /// differs from [VocabWord.fromFirestore]'s fail-loud style, which is
  /// appropriate there because it parses one document read triggered by
  /// one direct user action, not a bulk file — mirrors this app's broader
  /// graceful-degradation philosophy (`DESIGN_REFERENCE.md` §5.8) instead.
  /// The catch is deliberately broad (`catch (_)`) since any failure mode
  /// here — a bad cast, a missing field, the explicit empty-meanings
  /// check above — should be treated the same way: skip this one entry,
  /// keep going.
  static List<VocabBundleEntry> listFromJson(List<dynamic> jsonArray) {
    final entries = <VocabBundleEntry>[];
    for (final raw in jsonArray) {
      try {
        entries.add(VocabBundleEntry.fromMap(raw as Map<String, dynamic>));
      } catch (_) {
        continue;
      }
    }
    return entries;
  }
}
