// GENERATED by tools/vocab_import/bin/generate_bundles.js — do not hand-edit.
// Regenerate via: node tools/vocab_import/bin/generate_bundles.js

/// Timestamp the current `assets/vocab/*.json` bundle files were generated
/// at (`DATA_MODEL.md` §11.3) — the delta query in
/// `VocabBundleService.fetchDelta` uses this to find only vocabulary
/// documents changed *after* the bundle was built.
final DateTime kBundleGeneratedAt = DateTime.fromMillisecondsSinceEpoch(1787677024973);
